version: '3.4'

services:
  app:
    build: .
    container_name: fiap-soat-project_project_api
    environment:
      - DB_HOST=db
      - DB_USERNAME=user_tech
      - DB_PASSWORD=testtest
      - DB_NAME=fiap-soat-project_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - fiap-project-network
  db:
    image: mysql
    container_name: fiap-soat-project_db
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=fiap-soat-project_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - fiap-project-network

volumes:
   db:

networks:
  fiap-project-network:
    driver: bridge