server:
  port: 8080
spring:
  application:
    name: taste-food
  cloud:
    openfeign:
      client:
        config:
          mercadopago:
            defaultRequestHeaders:
              authorization: Bearer ${mercadopago.api.accessToken}
            url: ${mercadopago.api.url}
  datasource:
    url: jdbc:postgresql://localhost:5432/taste_food
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
mercadopago:
  api:
    url: https://api.mercadopago.com
    userId: fake
    posId: fake
    accessToken: fake
    callbackUrl: fake
