server:
  port: 9093
spring:
  application:
    name: taste-food
  cloud:
    openfeign:
      client:
        config:
          customer:
            url: ${application.customer.url}
          payment:
            url: ${application.payment.url}
  datasource:
    url: jdbc:postgresql://localhost:5432/taste_food
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  rabbitmq:
    addresses: amqps://b-6b369879-a388-49f0-8c8b-505e9ee77db3.mq.us-east-1.amazonaws.com:5671
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

application:
  customer:
    url: http://localhost:9091
  payment:
    url: http://localhost:9092
  queue:
    paymentStatusChanged:
      name: payment-status-changed
