server:
  port: 9093
spring:
  application:
    name: taste-food
  cloud:
    openfeign:
      client:
        config:
          customer:
            url: ${application.customer-api.url}
          payment:
            url: ${application.payment-api.url}
  datasource:
    url: jdbc:postgresql://localhost:5432/taste_food
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

application:
  customer-api:
    url: http://localhost:9091
  payment-api:
    url: http://localhost:9092
  queue:
    payment-status-changed:
      name: payment-status-changed
