apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: taste-food
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taste-food
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50