apiVersion: v1
kind: Secret
metadata:
  name: taste-food
type: Opaque
data:
  SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
  SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
  SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
  MERCADOPAGO_API_USERID: ${MERCADOPAGO_API_USERID}
  MERCADOPAGO_API_POSID: ${MERCADOPAGO_API_POSID}
  MERCADOPAGO_API_ACCESSTOKEN: ${MERCADOPAGO_API_ACCESSTOKEN}
  MERCADOPAGO_API_CALLBACKURL: ${MERCADOPAGO_API_CALLBACKURL}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_REGION: ${AWS_REGION}